version: '3'
#実験環境の統一のため全て同じポートを利用している。適宜コメントアウトして利用する。
services:
  http1.1:
    build:
        context: .
        dockerfile: ./http1.1/Dockerfile
    ports:
      - "8081:80"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
          pids: 100

  http2:
    build:
        context: .
        dockerfile: ./http2/Dockerfile
    ports:
      - "8082:443"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
          pids: 100